management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  temporal:
    connection:
      target: local
    namespace: gojha
    workers-auto-discovery:
      packages: dev.gauravojha.learningtemporal
    start-workers: true